config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'toppages/index'
  root to: "toppages#index"
  
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  
  get "signup", to: "users#new"
  get "items/:id/attention", to: "items#attention", as: "attention"
  
  resources :users
  resources :items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  
  validates :name, presence: true, length: { maximum: 50 }
  validates :url, presence: true
  validates :price, presence: true, numericality: true
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  mount_uploader :image, ImageUploader
  has_many :items, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  include SessionsHelper
  
  private
  
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :require_user_logged_in, only: [:destroy, :edit]
  before_action :currect_user, only: [:destroy]
  
  def index
    @items = Item.order(id: :desc)
  end
  
  def show
    @item = Item.find(params[:id])
  end
  
  def new
    @item = Item.new
  end
 
  def create
    @user = current_user
    @item = current_user.items.build(item_params)
    if @item.save
      flash[:success] = "アイテムを登録しました。"
      redirect_to root_url
    else
      @items = current_user.items.order(id: :desc).page(params[:page])
      flash.now[:danger] = "アイテムの登録に失敗しました。"
      render :new
    end
  end
  
  def destroy
    @item.destroy
    flash[:sucesss] = "アイテムを削除しました。"
    render :new
  end
  
  def edit
    @item = Item.find(params[:id])
  end
 
  def update
    @item = Item.find(params[:id])
   
    if @item.update(item_params)
      flash[:sucesss] = "アイテム情報を更新しました。"
      redirect_to @item
    else
      flash.now[:danger] = "アイテム情報を更新できませんでした。"
      render :edit
    end
  end
  
  def attention
    @item = Item.find(params[:id])
  end
  

  private
  
  def item_params
    params.require(:item).permit(:name, :url, :comment, :price, :image)
  end
  
  def currect_user
    @item = current_user.items.find_by(id: params[:id])
    unless @item
      redirect_to root_url
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = "ログインに成功しました。"
      redirect_to @user
    else
      flash[:danger] = "ログインに失敗しました。"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:sucess] = "ログアウトしました。"
    redirect_to root_url
  end
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      #ログイン成功
      session[:user_id] = @user.id
      return true
    else
      #ログイン失敗
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    @users = User.order(id: :desc)
    @items = Item.order(id: :desc)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:destroy, :edit]

  def index
    @users = User.order(id: :desc)
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = "ユーザー登録しました。"
      redirect_to sessions_new_path
    else
      flash.now[:danger] = "ユーザー登録に失敗しました。"
      render :new
    end
  end
  
  def destroy
    @user = current_user #機能はしてるが適切ではない？
    @user.destroy
    flash[:success] = "退会しました。"
    render :new
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "ユーザー情報を更新しました"
      redirect_to @user
    else
      flash.now[:danger] = "ユーザー情報を更新できませんでした"
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :birthday, :comment, :sex)
  end
  
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
end

app/views/items/_items.html.erb
<% if items.any? %>
    <% items.each do |item| %>
      <div class="card sm-3" style="max-width: 540px">
        <div class="row no-gutters">
          <div class="col-sm-4 my-auto" style="text-align: center">
            <% if item.image? %>
              <%= link_to image_tag(item.image.to_s, alt: "Item image", :width => "50%", :height => "auto"), item_path(item) %>
            <% else %>
              <%= link_to image_tag("default.jpg", alt: "Item image", :width => "50%", :height => "auto"), item_path(item) %>
            <% end %>
          </div>
          <div class="col-sm-8">
            <div class="card-body">
              <h4 class="card-title"><%= item.name.truncate(20) %></h4>
              <p class="card-text"><%= item.comment.truncate(50) %></p>
              <p><%= link_to 'Onedari詳細', item_path(item) %></p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
<% end %>

app/views/items/attention.html.erb
<div class="text-center">
  <% url = "https://www.amazon.jp/hz/wishlist/ls/#{@item.url}" %>
  <h1>Amazonへ移動します</h1>
  <h2><%= url %></h2>
    <%= link_to "移動する", url, class: "btn btn-lg btn-primary" %>
</div>

app/views/items/edit.html.erb
<h1>Onedari編集</h1>
<%= form_for @item do |f| %>
 <%= render "layouts/error_messages", model: f.object %>
 <% if @item.image? %>
   <%= image_tag @item.image.url, alt: "Item image", :width => "20%", :height => "auto" %>
 <% else %>
   <%= image_tag "default.jpg", alt: "item image", :width => "20%", :height => "auto" %>
 <% end %>
   <button type="button" class="btn btn-outline-secondary rounded-pill">
     <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png" %>
   </button>
 <p>
   <%= f.label(:name, "名前") %>
   <%= f.text_field :name %>
 </p>
 <p>
   <%= f.label(:url, "URL") %>
   <%= f.text_field :url %>
 </p>
 <p>
   <%= f.label(:price, "プライス") %>
   <%= f.text_field :price %>
 </p>
 <p>
   <%= f.label(:comment, "コメント") %>
   <%= f.text_field :comment %>
 </p>

 <%= f.submit "編集完了" %>
<% end %>

app/views/items/index.html.erb
<h1>Onedari一覧</h1>
<%= render 'items', items: @items %>

app/views/items/new.html.erb
<div class="text-center">
  <h1>Onedari登録</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">
    <%= form_with(model: @item, local: true) do |f| %>
      <%= render "layouts/error_messages", model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, 'Onedariするもの' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      
        <div class="form-group">
          <i class="fab fa-amazon", style="margin-right: 10px;"></i><%= f.label :url, 'https://www.amazon.jp/hz/wishlist/ls/' %>
          <%= f.text_field :url, :placeholder => "上記URLに続く文字列を入力（Amazonほしい物リストのURL）", class: 'form-control' %>
        </div>
      
      <div class="form-group">
        <i class="fas fa-yen-sign", style="margin-right: 10px;"></i><%= f.label :price %>
        <%= f.text_field :price, class: 'form-control' %>
      </div>

      <div class="form-group">
        <i class="far fa-comment", style="margin-right: 10px;"></i><%= f.label :comment %>
        <%= f.text_field :comment, class: 'form-control' %>
      </div>

      <%= f.submit 'アイテム登録', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/items/show.html.erb
<h1>Onedari詳細</h1>
<div class="row">
  <div class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><label style="margin-right: 10px;">名前</label><%= @item.name %></h3>
        <ul style="list-style: none;">
          <li style="text-align: center">
             <% if @item.image? %>
               <%= link_to image_tag(@item.image.to_s, alt: "Item image", :width => "50%", :height => "auto"), item_path(@item) %>
             <% else %>
               <%= link_to image_tag("default.jpg", alt: "Item image", :width => "50%", :height => "auto"), item_path(@item) %>
             <% end %>
          </li>
          <li><label style="margin-right: 10px;"><i class="fab fa-amazon"></i></label><%= @item.url %></li>
          <li><label style="margin-right: 10px;"><i class="fas fa-yen-sign"></i></label><%= @item.price %></li>
          <li><label style="margin-right: 10px;"><i class="far fa-comment"></i></label><%= @item.comment %></li>
        </ul>
      </div>
      <% if current_user == @item.user %>
        <%= link_to "編集", edit_item_path, class: "btn btn-lg btn-primary" %>
        <%= link_to "削除", @item, method: :delete, data: { confirm: "You sure?" }, class: "btn btn-lg btn-danger" %>
      <% end %>
      <%= link_to "Onedariユーザー", @item.user, class: "btn btn-lg btn-link" %>
      <%= link_to "支援する", attention_path(@item), data: { confirm: "支援をしますか？" }, class: "btn btn-lg btn-primary" %>
    </div>
  </div>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">onedari屋</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item"><%= link_to 'ユーザー一覧', users_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to "Onedari一覧", items_path, class: "nav-link" %></li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'My profile', user_path(current_user) %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to "Logout", logout_path, method: :delete %></li>
              <li class="dropdown-item"><%= link_to "user_edit", edit_user_path(current_user) %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to 'Signup', signup_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Login', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html  lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Onedari</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/toppages/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h2>新着Onedari</h2>
    <%= render "items/items", items: @items %>
  </div>
  <div class="col-sm-6">
    <h2>新着ユーザー</label></h2>
    <%= render "users/users", users: @users %>
  </div>
</div>

app/views/users/_users.html.erb
<% if users.any? %>
    <% users.each do |user| %>
      <div class="card sm-3" style="max-width: 540px">
        <div class="row no-gutters">
          <div class="col-sm-4 my-auto" style="text-align: center">
            <% if user.image? %>
              <%= link_to image_tag(user.image.to_s, alt: "User image", :width => "50%", :height => "auto"), user_path(user) %>
            <% else %>
              <%= link_to image_tag("default.jpg", alt: "User image", :width => "50%", :height => "auto"), user_path(user) %>
            <% end %>
          </div>
          <div class="col-sm-8">
            <div class="card-body">
              <h4 class="card-title"><%= user.name.truncate(20) %></h4>
              <p class="card-text"><%= user.comment.to_s.truncate(50) %></p>
              <p><%= link_to 'プロフィール', user_path(user) %></p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
<% end %>

app/views/users/edit.html.erb
<h1>ユーザー編集</h1>
<%= form_for @user do |f| %>
 <% if @user.image? %>
   <%= image_tag @user.image.url, alt: "User image", :width => "20%", :height => "auto" %>
 <% else %>
   <%= image_tag "default.jpg", alt: "User image", :width => "20%", :height => "auto" %>
 <% end %>
   <button type="button" class="btn btn-outline-secondary rounded-pill">
     <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png" %>
   </button>
 <p>
   <%= f.label(:name, "名前") %>
   <%= f.text_field :name %>
 </p>
 <p>
   <%= f.label(:sex, "性別") %>
   <%= f.text_field :sex %>
 </p>
 <p>
   <%= f.label(:birthday, "生年月日") %>
   <%= f.text_field :birthday %>
 </p>
 <p>
   <%= f.label(:comment, "コメント") %>
   <%= f.text_field :comment %>
 </p>
 <p>
   <%= f.label(:email, "メールアドレス") %>
   <%= f.text_field :email %>
 </p>
 <p>
   <%= f.label :password, "パスワード" %>
   <%= f.password_field :password %>
 </p>
 <p>
   <%= f.label :password_confirmation, "パスワード再入力" %>
   <%= f.password_field :password_confirmation %>
 </p>
 
 <%= f.submit "編集完了" %>
<% end %>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>
<%= render "users", users: @users %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
      <%= render "layouts/error_messages", model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-sm-6">
    <h2>ユーザー詳細</h2>
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><label style="margin-right: 10px;">名前</label><%= @user.name %></h3>
        <ul style="list-style: none;">
          <li style="text-align: center">
             <% if @user.image? %>
               <%= image_tag @user.image.to_s, alt: "User image", :width => "50%", :height => "auto" %>
             <% else %>
               <%= image_tag "default.jpg", alt: "User image", :width => "50%", :height => "auto" %>
             <% end %>
          </li>
          <li><label style="margin-right: 10px;"><i class="fas fa-transgender-alt"></i></label><%= @user.sex %></li>
          <li><label style="margin-right: 10px;"><i class="fas fa-birthday-cake"></i></label><%= @user.birthday %></li>
          <li><label style="margin-right: 10px;"><i class="far fa-comment"></i></label><%= @user.comment %></li>
        </ul>
      </div>
      <% if current_user == @user %>
        <%= link_to "Onedariする", new_item_path, class: "btn btn-lg btn-primary" %>
        <%= link_to "編集", edit_user_path, class: "btn btn-lg btn-primary" %>
        <%= link_to "退会", @user, method: :delete, data: { confirm: "You sure?" }, class: "btn btn-lg btn-danger" %>
      <% end %>
    </div>
  </div>
  <div class="col-sm-6">
    <h2>Onedari一覧</h2>
    <% @user.items.each do |item| %>
      <div class="card sm-3" style="max-width: 540px">
        <div class="row no-gutters">
          <div class="col-sm-4 my-auto" style="text-align: center">
            <% if item.image? %>
              <%= link_to image_tag(item.image.to_s, alt: "Item image", :width => "50%", :height => "auto"), item_path(item) %>
            <% else %>
              <%= link_to image_tag("default.jpg", alt: "Item image", :width => "50%", :height => "auto"), item_path(item) %>
            <% end %>
          </div>
          <div class="col-sm-8">
            <div class="card-body">
              <h4 class="card-title"><%= item.name %></h4>
              <p class="card-text"><%= item.comment.truncate(50) %></p>
              <p><%= link_to 'Onedari詳細', item_path(item) %></p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>